sudo: required

services:
  - docker

language: node_js

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run test-ci

after_success:
  - npm run build-prod
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t "$DOCKER_IMAGE" .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$DOCKER_IMAGE";
    fi

